"""visitor_management

Revision ID: 2b0147f58818
Revises: ff2627f3957a
Create Date: 2026-09-30 10:45:19.709787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0147f58818'
down_revision: Union[str, Sequence[str], None] = 'ff2627f3957a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('identification_type', sa.Enum('NATIONAL_ID', 'PASSPORT', 'DRIVER_LICENSE', 'OTHER', name='identificationtype'), nullable=False),
    sa.Column('identification_number', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_identification_number'), 'visitors', ['identification_number'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('host_user_id', sa.UUID(), nullable=False),
    sa.Column('checkin_gate_id', sa.UUID(), nullable=True),
    sa.Column('checkout_gate_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHECKED_IN', 'CHECKED_OUT', 'EXPIRED', 'CANCELLED', name='visitstatus'), nullable=False),
    sa.Column('qr_code_value', sa.String(length=255), nullable=True),
    sa.Column('expected_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkin_gate_id'], ['gates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checkout_gate_id'], ['gates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_checkin_gate_id'), 'visits', ['checkin_gate_id'], unique=False)
    op.create_index(op.f('ix_visits_checkout_gate_id'), 'visits', ['checkout_gate_id'], unique=False)
    op.create_index(op.f('ix_visits_host_user_id'), 'visits', ['host_user_id'], unique=False)
    op.create_index(op.f('ix_visits_qr_code_value'), 'visits', ['qr_code_value'], unique=True)
    op.create_index(op.f('ix_visits_visitor_id'), 'visits', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visitor_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_qr_code_value'), table_name='visits')
    op.drop_index(op.f('ix_visits_host_user_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_checkout_gate_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_checkin_gate_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_visitors_identification_number'), table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###
